"""Curated Batch 23 Indian Industrial Manufacturing Companies.
Guaranteed Zero Overlap with Batches 1-22 (Total 50 accounts).
Prepared specifically for Scaled Trigger Recovery Validation (Phase 12).
"""
from typing import Dict, List

BATCH_23_COMPANIES: List[Dict[str, str]] = [
    {
        "name": "Som Distilleries and Breweries Limited",
        "domain": "somindia.com",
        "sector": "Brewing & Distilling Plants",
        "primary_hub": "Bhopal Madhya Pradesh / Hassan",
    },
    {
        "name": "Sheela Foam Limited",
        "domain": "sheelafoam.com",
        "sector": "Polyurethane Foam & Industrial Cushioning",
        "primary_hub": "Greater Noida / Hyderabad / Jalpaiguri",
    },
    {
        "name": "Clean Science and Technology Limited",
        "domain": "cleanscience.co.in",
        "sector": "Specialty Chemical Catalysis & MEHQ/BHA",
        "primary_hub": "Kurkumbh Pune Maharashtra",
    },
    {
        "name": "Innovators Facade Systems Limited",
        "domain": "innovators.in",
        "sector": "Facade Engineering & Aluminium Glazing Systems",
        "primary_hub": "Pen Raigad Maharashtra",
    },
    {
        "name": "Shankara Building Products Limited",
        "domain": "shankarabuildpro.com",
        "sector": "Steel Processing & Construction Building Materials",
        "primary_hub": "Bengaluru / Hyderabad / Chennai",
    },
    {
        "name": "PTC Industries Limited",
        "domain": "ptcil.com",
        "sector": "Titanium & Superalloy Castings for Aerospace",
        "primary_hub": "Lucknow Uttar Pradesh",
    },
    {
        "name": "Rolex Rings Limited",
        "domain": "rolexrings.com",
        "sector": "Forged & Machined Bearing Rings & Automotive Components",
        "primary_hub": "Rajkot Gujarat",
    },
    {
        "name": "Craftsman Automation Limited",
        "domain": "craftsmanautomation.com",
        "sector": "Precision Machining, Cylinder Blocks & Storage Systems",
        "primary_hub": "Coimbatore Tamil Nadu",
    },
    {
        "name": "Sansera Engineering Limited",
        "domain": "sansera.in",
        "sector": "Connecting Rods, Crankshafts & Aerospace Precision Components",
        "primary_hub": "Bengaluru Karnataka",
    },
    {
        "name": "Lumax Auto Technologies Limited",
        "domain": "lumaxworld.in",
        "sector": "Gear Shifters, Lighting & Metallic Components",
        "primary_hub": "Chakan Pune / Manesar",
    },
    {
        "name": "Pricol Limited",
        "domain": "pricol.com",
        "sector": "Instrument Clusters, Telematics & Automotive Sensors",
        "primary_hub": "Coimbatore Tamil Nadu",
    },
    {
        "name": "Minda Corporation Limited",
        "domain": "sparkminda.com",
        "sector": "Security Systems, Wiring Harnesses & Die Castings",
        "primary_hub": "Greater Noida / Pune",
    },
    {
        "name": "Piccadily Sugar and Allied Industries Limited",
        "domain": "picadily.com",
        "sector": "Sugar Manufacturing & Molasses Products",
        "primary_hub": "Patiala Punjab",
    },
    {
        "name": "Kesar Enterprises Limited",
        "domain": "kesarindia.com",
        "sector": "Sugar, Power & Industrial Spirits",
        "primary_hub": "Baheri Bareilly Uttar Pradesh",
    },
    {
        "name": "Empee Sugars and Chemicals Limited",
        "domain": "empeegroup.co.in",
        "sector": "Industrial Alcohol & Sugar Production",
        "primary_hub": "Ambasamudram Tamil Nadu",
    },
    {
        "name": "Thiru Arooran Sugars Limited",
        "domain": "tasugars.com",
        "sector": "Sugar Processing & Bagasse Power",
        "primary_hub": "Thirumandankudi Tamil Nadu",
    },
    {
        "name": "Empire Industries Limited",
        "domain": "empiremetals.com",
        "sector": "Amber Glass Bottles & Industrial Containers",
        "primary_hub": "Vitthalwadi Thane Maharashtra",
    },
    {
        "name": "Shiva Granito India Limited",
        "domain": "shivagranito.com",
        "sector": "Engineered Quartz Stone & Agglomerated Marble",
        "primary_hub": "Udaipur Rajasthan",
    },
    {
        "name": "Aro Granite Industries Limited",
        "domain": "arogranite.com",
        "sector": "Granite Tiles & Slabs Export Processing",
        "primary_hub": "Hosur Tamil Nadu",
    },
    {
        "name": "Pacific Industries Limited",
        "domain": "pacificindustriesltd.com",
        "sector": "Granite & Natural Stone Processing",
        "primary_hub": "Bedla Udaipur Rajasthan / Bengaluru",
    },
    {
        "name": "KLR Industries Limited",
        "domain": "klrindustries.com",
        "sector": "Drilling Rigs, Rock Rollers & Heavy Equipment",
        "primary_hub": "Hyderabad Telangana",
    },
    {
        "name": "Shilp Gravures Limited",
        "domain": "shilpgravures.com",
        "sector": "Gravure Printing Cylinders & Engraving Plates",
        "primary_hub": "Rakanpur Gandhinagar Gujarat",
    },
    {
        "name": "Walchand PeopleFirst Limited",
        "domain": "walchandgroup.com",
        "sector": "Industrial Precision Engineering Support",
        "primary_hub": "Mumbai Maharashtra",
    },
    {
        "name": "Kirloskar Oil Engines Limited",
        "domain": "koel.kirloskar.com",
        "sector": "Diesel Engines, Generating Sets & Farm Power",
        "primary_hub": "Kagal Kolhapur / Khadki Pune / Bhare",
    },
    {
        "name": "Swabhiman Agritech Limited",
        "domain": "swabhimanagritech.com",
        "sector": "Agro Seed Processing & Cold Storage Facilities",
        "primary_hub": "Purnia Bihar",
    },
    {
        "name": "Gujarat Ambuja Exports Limited",
        "domain": "gaelonline.com",
        "sector": "Maize Starch, Derivatives & Soya De-oiled Cake",
        "primary_hub": "Himmatnagar / Kadi / Sitarganj / Chalisgaon",
    },
    {
        "name": "Universal Starch-Chem Allied Limited",
        "domain": "universalstarch.com",
        "sector": "Maize Products, Starch & Derivatives",
        "primary_hub": "Dondaicha Dhule Maharashtra",
    },
    {
        "name": "KN Agri Resources Limited",
        "domain": "knagri.com",
        "sector": "Soya Solvent Extraction & Edible Oil Refining",
        "primary_hub": "Khandwa / Raipur Chhattisgarh",
    },
    {
        "name": "Kanpur Plastipack Limited",
        "domain": "kanplas.com",
        "sector": "FIBC Bulk Bags, Multifilament Yarn & Woven Sacks",
        "primary_hub": "Dada Nagar Kanpur Uttar Pradesh",
    },
    {
        "name": "Amber Enterprises India Limited",
        "domain": "ambergroupindia.com",
        "sector": "Air Conditioners, Heat Exchangers & Sheet Metal Components",
        "primary_hub": "Rajpura Punjab / Jhajjar / Pune / Kanchipuram",
    },
    {
        "name": "Dixon Applied Technologies Private Limited",
        "domain": "dixoninfo.com",
        "sector": "Home Appliance Manufacturing & Precision Tooling",
        "primary_hub": "Dehradun / Noida Uttar Pradesh",
    },
    {
        "name": "R R Kabel Limited",
        "domain": "rrkabel.com",
        "sector": "Building Wires, Industrial Cables & Copper Wire Rods",
        "primary_hub": "Waghodia Vadodara / Silvassa",
    },
    {
        "name": "Cordscable Industries Limited",
        "domain": "cordscable.com",
        "sector": "Instrumentation Cables & Control Cables",
        "primary_hub": "Chopanki / Kahrani Rajasthan",
    },
    {
        "name": "Surana Solar Limited",
        "domain": "suranasolar.com",
        "sector": "Solar Photovoltaic Modules & Power Generation",
        "primary_hub": "Cherlapally Hyderabad Telangana",
    },
    {
        "name": "Raghav Productivity Enhancers Limited",
        "domain": "rammingmass.com",
        "sector": "Silica Ramming Mass for Induction Furnaces",
        "primary_hub": "Newai Tonk Rajasthan",
    },
    {
        "name": "Ramkrishna Forgings Limited",
        "domain": "ramkrishnaforgings.com",
        "sector": "Forged Components for Automotive & Railways",
        "primary_hub": "Jamshedpur Jharkhand",
    },
    {
        "name": "Deccan Gold Mines Limited",
        "domain": "deccangoldmines.com",
        "sector": "Gold Exploration & Mineral Processing",
        "primary_hub": "Hutti / Dharwad Karnataka",
    },
    {
        "name": "Anupam Rasayan India Limited",
        "domain": "anupamrasayan.com",
        "sector": "Custom Synthesis & Specialty Fine Chemicals",
        "primary_hub": "Sachin / Jhagadia Surat Gujarat",
    },
    {
        "name": "Shyam Metalics and Energy Limited",
        "domain": "shyammetalics.com",
        "sector": "Pellets, Sponge Iron, Billets & Long Products",
        "primary_hub": "Sambalpur Odisha / Jamuria WB",
    },
    {
        "name": "Stovec Industries Limited",
        "domain": "stovec.com",
        "sector": "Textile Printing Machinery & Perforated Screens",
        "primary_hub": "Naroda Ahmedabad Gujarat",
    },
    {
        "name": "Kilburn Engineering Limited",
        "domain": "kilburnengg.com",
        "sector": "Industrial Drying Systems & Heavy Process Equipment",
        "primary_hub": "Saravali Kalyan Maharashtra",
    },
    {
        "name": "Davangere Sugar Company Limited",
        "domain": "davangeresugar.com",
        "sector": "Sugar Refining, Co-generation & Ethanol Units",
        "primary_hub": "Kukkawada Davangere Karnataka",
    },
    {
        "name": "Concord Control Systems Limited",
        "domain": "concordcs.com",
        "sector": "Railway Coach Electrical Systems & Battery Chargers",
        "primary_hub": "Lucknow Uttar Pradesh",
    },
    {
        "name": "Sona Hi Soni Healthcare Limited",
        "domain": "sonahisoni.com",
        "sector": "Medical Disposables & Surgical Consumables",
        "primary_hub": "Ahmedabad Gujarat",
    },
    {
        "name": "Ganesh Green Bharat Limited",
        "domain": "ganeshgreen.com",
        "sector": "Solar Module Manufacturing & Electrical EPC",
        "primary_hub": "Ahmedabad Gujarat",
    },
    {
        "name": "Alufluoride Limited",
        "domain": "alufluoride.com",
        "sector": "Aluminium Fluoride & Specialty Chemicals",
        "primary_hub": "Visakhapatnam Andhra Pradesh",
    },
    {
        "name": "Vikram Thermo (India) Limited",
        "domain": "vikramthermo.com",
        "sector": "Pharma Polymers & Specialty Methacrylate Excipients",
        "primary_hub": "Chhatral Gandhinagar Gujarat",
    },
    {
        "name": "Kanchi Karpooram Limited",
        "domain": "kanchikarpooram.com",
        "sector": "Camphor & Pine Chemicals",
        "primary_hub": "Kanchipuram Tamil Nadu",
    },
    {
        "name": "Jayvee Organics Private Limited",
        "domain": "jayveeorganics.com",
        "sector": "Pharma Intermediates & Fine Chemicals",
        "primary_hub": "Ankleshwar Gujarat",
    },
    {
        "name": "Airox Technologies Limited",
        "domain": "airoxtechnologies.com",
        "sector": "Pressure Swing Adsorption Oxygen Generators",
        "primary_hub": "Aurangabad Maharashtra",
    },
]
