"""Curated Batch 22 Indian Industrial Manufacturing Companies (Guaranteed Zero Overlap with Batches 1-21).
Prepared specifically for Upstream Trigger Quality Recovery Validation (Phase 11).
"""
from typing import Dict, List

BATCH_22_COMPANIES: List[Dict[str, str]] = [
    {
        "name": "Alicon Castalloy Limited",
        "domain": "alicongroup.com",
        "sector": "Aluminium Castings & Cylinder Heads",
        "primary_hub": "Chakan Pune",
    },
    {
        "name": "Auto Corporation of Goa Limited",
        "domain": "acglgoa.com",
        "sector": "Bus Bodies & Sheet Metal Components",
        "primary_hub": "Bhuimpal Sattari Goa",
    },
    {
        "name": "Commercial Engineers & Body Builders Co Limited",
        "domain": "cebbco.com",
        "sector": "Railway Wagons & Heavy Commercial Vehicle Bodies",
        "primary_hub": "Jabalpur Madhya Pradesh",
    },
    {
        "name": "Duroflex Private Limited",
        "domain": "duroflexworld.com",
        "sector": "Polyurethane Foam & Industrial Mattresses",
        "primary_hub": "Hosur Tamil Nadu",
    },
    {
        "name": "GKN Driveline (India) Limited",
        "domain": "gknautomotive.com",
        "sector": "Constant Velocity Joints & Driveline Systems",
        "primary_hub": "Dharuhera Haryana / Oragadam",
    },
    {
        "name": "GNA Gears Limited",
        "domain": "gnagears.com",
        "sector": "Automotive Transmission Gears & Shafts",
        "primary_hub": "Phagwara Punjab",
    },
    {
        "name": "Hi-Tech Gears Limited",
        "domain": "thehitechgears.com",
        "sector": "Engine Precision Gears & Transmission Components",
        "primary_hub": "Bhiwadi Rajasthan / Manesar",
    },
    {
        "name": "India Motor Parts and Accessories Limited",
        "domain": "impal.net",
        "sector": "Automobile Parts Distribution & Logistics",
        "primary_hub": "Chennai Tamil Nadu",
    },
    {
        "name": "IP Rings Limited",
        "domain": "iprings.com",
        "sector": "Piston Rings & Transmission Orbital Cold Formed Parts",
        "primary_hub": "Maraimalai Nagar Chennai",
    },
    {
        "name": "Jamna Auto Industries Limited",
        "domain": "jaispring.com",
        "sector": "Automotive Tapered Leaf Springs & Parabolic Springs",
        "primary_hub": "Yamunanagar / Malanpur / Jamshedpur",
    },
    {
        "name": "L.G. Balakrishnan & Bros Limited",
        "domain": "lgb.co.in",
        "sector": "Roller Chains, Sprockets & Industrial Conveyor Belts",
        "primary_hub": "Coimbatore Tamil Nadu",
    },
    {
        "name": "Menon Pistons Limited",
        "domain": "menonpistons.com",
        "sector": "Aluminium Alloy Pistons & Gudgeon Pins",
        "primary_hub": "Shiroli Kolhapur Maharashtra",
    },
    {
        "name": "Prabhat Technologies (India) Limited",
        "domain": "prabhatgroup.net",
        "sector": "Telecom Products & Mobile Accessories",
        "primary_hub": "Mumbai Maharashtra",
    },
    {
        "name": "Remsons Industries Limited",
        "domain": "remsons.com",
        "sector": "Auto Control Cables, Gear Shift Systems & Winches",
        "primary_hub": "Daman / Gurugram / Pune",
    },
    {
        "name": "Samkrg Pistons and Rings Limited",
        "domain": "samkrg.com",
        "sector": "Pistons, Piston Pins & Piston Rings",
        "primary_hub": "Bonthapally Hyderabad Telangana",
    },
    {
        "name": "Shivani Detergents Private Limited",
        "domain": "shivanidetergents.com",
        "sector": "Industrial Detergents & Surfactants",
        "primary_hub": "Indore Madhya Pradesh",
    },
    {
        "name": "Sharda Motor Industries Limited",
        "domain": "shardamotor.com",
        "sector": "Automotive Exhaust Systems & Catalytic Converters",
        "primary_hub": "Greater Noida UP / Chennai",
    },
    {
        "name": "Standard Radiators Limited",
        "domain": "standardradiators.com",
        "sector": "Heat Exchangers, Industrial Radiators & Oil Coolers",
        "primary_hub": "Vadodara Gujarat",
    },
    {
        "name": "Steel Strips Wheels Limited",
        "domain": "sswlindia.com",
        "sector": "Steel & Alloy Wheel Rims for Passenger Cars & Trucks",
        "primary_hub": "Dappar Punjab / Chennai / Mehsana",
    },
    {
        "name": "GTL Infrastructure Limited",
        "domain": "gtlinfra.com",
        "sector": "Telecom Tower Passive Infrastructure",
        "primary_hub": "Navi Mumbai Maharashtra",
    },
    {
        "name": "Vakrangee Limited",
        "domain": "vakrangee.in",
        "sector": "E-Governance Services & Hardware Terminals",
        "primary_hub": "Mumbai Maharashtra",
    },
    {
        "name": "Premier Energies Limited",
        "domain": "premierenergies.com",
        "sector": "Solar Cells & Solar Photovoltaic Module Assembly",
        "primary_hub": "Maheshwaram Hyderabad Telangana",
    },
    {
        "name": "Waaree Energies Limited",
        "domain": "waaree.com",
        "sector": "Solar Panels, Inverters & Solar Thermal Products",
        "primary_hub": "Surat / Chikhli Gujarat / Greater Noida",
    },
    {
        "name": "Suzlon Energy Limited",
        "domain": "suzlon.com",
        "sector": "Wind Turbines, Tubular Steel Towers & Hybrid Lattice",
        "primary_hub": "Daman / Chakan Pune / Bhuj Gujarat",
    },
    {
        "name": "Adani Green Energy Limited",
        "domain": "adanigreenenergy.com",
        "sector": "Solar & Wind Power Plants & Hybrid Energy Parks",
        "primary_hub": "Khavda Kutch Gujarat",
    },
    {
        "name": "Tata Power Solar Systems Limited",
        "domain": "tatapowersolar.com",
        "sector": "Solar Cell & Module Manufacturing & Microgrids",
        "primary_hub": "Tirunelveli Tamil Nadu / Bengaluru",
    },
    {
        "name": "Goldi Solar Private Limited",
        "domain": "goldisolar.com",
        "sector": "Solar PV Modules, Micro-Inverters & Cell Assembly",
        "primary_hub": "Navsari Gujarat / Surat",
    },
    {
        "name": "Emmvee Photovoltaic Power Private Limited",
        "domain": "emmvee.com",
        "sector": "Solar PV Modules, Water Heaters & Clean Energy",
        "primary_hub": "Dasanapura Bengaluru Karnataka",
    },
    {
        "name": "RenewSys India Private Limited",
        "domain": "renewsysworld.com",
        "sector": "Solar Encapsulants (EVA/POE) & Backsheets",
        "primary_hub": "Patalganga Maharashtra / Hyderabad",
    },
    {
        "name": "SJVN Limited",
        "domain": "sjvn.nic.in",
        "sector": "Hydro Electric Power, Solar Power & Transmission",
        "primary_hub": "Shimla Himachal Pradesh",
    },
    {
        "name": "NHPC Limited",
        "domain": "nhpcindia.com",
        "sector": "Hydroelectric Power Generation & Substation Infra",
        "primary_hub": "Faridabad Haryana",
    },
    {
        "name": "THDC India Limited",
        "domain": "thdc.co.in",
        "sector": "Hydro Power Projects & Thermal Power Stations",
        "primary_hub": "Rishikesh Uttarakhand",
    },
    {
        "name": "NEEPCO Limited",
        "domain": "neepco.co.in",
        "sector": "Hydro & Thermal Power Plants in North East",
        "primary_hub": "Shillong Meghalaya",
    },
    {
        "name": "NTPC Green Energy Limited",
        "domain": "ntpc.co.in",
        "sector": "Renewable Energy Parks & Green Hydrogen Hubs",
        "primary_hub": "New Delhi",
    },
    {
        "name": "Nava Limited",
        "domain": "navalimited.com",
        "sector": "Ferro Alloys, Power Generation & Sugar Refining",
        "primary_hub": "Paloncha Kothagudem Telangana / Odisha",
    },
    {
        "name": "Tata Steel Long Products Limited",
        "domain": "tatasteellp.com",
        "sector": "Sponge Iron, Special Steel Billets & Wire Rods",
        "primary_hub": "Gamharia Jamshedpur Jharkhand",
    },
    {
        "name": "DP Wires Limited",
        "domain": "dpwires.co.in",
        "sector": "LRPC Steel Wires, Induction Hardened Wires",
        "primary_hub": "Ratlam Madhya Pradesh",
    },
    {
        "name": "Kakatiya Cement Sugar and Industries Limited",
        "domain": "kakatiyacements.com",
        "sector": "Cement Manufacturing & White Crystal Sugar",
        "primary_hub": "Peruvancha Khammam Telangana",
    },
    {
        "name": "Indo Farm Equipment Limited",
        "domain": "indofarm.in",
        "sector": "Tractors & Heavy Construction Machinery",
        "primary_hub": "Baddi Solan Himachal Pradesh",
    },
    {
        "name": "Captain Tractors Private Limited",
        "domain": "captaintractors.com",
        "sector": "Mini Tractors & Agricultural Implements",
        "primary_hub": "Rajkot Gujarat",
    },
    {
        "name": "Ingersoll Rand (India) Limited",
        "domain": "ingersollrand.com",
        "sector": "Industrial Air Compressors & Blowers",
        "primary_hub": "Naroda Ahmedabad Gujarat",
    },
    {
        "name": "Mazda Limited",
        "domain": "mazdalimited.com",
        "sector": "Vacuum Systems, Evaporators & Control Valves",
        "primary_hub": "Naroda Ahmedabad Gujarat",
    },
    {
        "name": "Pennar Industries Limited",
        "domain": "pennarindia.com",
        "sector": "Pre-Engineered Buildings & Cold Rolled Steel",
        "primary_hub": "Patancheru Hyderabad Telangana",
    },
    {
        "name": "Man Industries (India) Limited",
        "domain": "mangroup.com",
        "sector": "LSAW & HSAW Large Diameter Carbon Steel Pipes",
        "primary_hub": "Anjar Kutch Gujarat / Pithampur",
    },
    {
        "name": "Nahar Industrial Enterprises Limited",
        "domain": "owmnahar.com",
        "sector": "Yarns, Fabrics & Garments",
        "primary_hub": "Lalru SAS Nagar Punjab / Ambala",
    },
    {
        "name": "AIA Engineering Limited",
        "domain": "aiaengineering.com",
        "sector": "High Chrome Grinding Media & Mill Liners",
        "primary_hub": "Moraiya Ahmedabad Gujarat",
    },
    {
        "name": "Dynamatic Technologies Limited",
        "domain": "dynamatics.com",
        "sector": "Aerospace Hydraulic & Precision Engineering",
        "primary_hub": "Peenya Bengaluru Karnataka",
    },
    {
        "name": "Suprajit Engineering Limited",
        "domain": "suprajit.com",
        "sector": "Mechanical Control Cables & Halogen Lamps",
        "primary_hub": "Bommasandra Bengaluru Karnataka",
    },
    {
        "name": "Sandhar Technologies Limited",
        "domain": "sandhargroup.com",
        "sector": "Automotive Locking Systems & Die Casting",
        "primary_hub": "Gurugram Haryana / Bawal",
    },
    {
        "name": "Gabriel India Limited",
        "domain": "anandgroupindia.com",
        "sector": "Ride Control Products & Shock Absorbers",
        "primary_hub": "Chakan Pune Maharashtra",
    },
]
