"""full_crm_upgrade

Revision ID: 7d50452ffcaa
Revises: 85a9a288beac
Create Date: 2026-05-26 09:35:06.023333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d50452ffcaa'
down_revision: Union[str, None] = '85a9a288beac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('contact_person', sa.String(length=300), nullable=True))
    op.add_column('companies', sa.Column('division', sa.String(length=300), nullable=True))
    op.add_column('companies', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('lead_status', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('last_contact_date', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('next_followup_date', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('order_received', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('order_date', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('po_number', sa.String(length=300), nullable=True))
    op.add_column('companies', sa.Column('order_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('companies', sa.Column('billing_status', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('payment_status', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('email_sent', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('whatsapp_sent', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('reply_received', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('bounced_email', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('automation_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'automation_enabled')
    op.drop_column('companies', 'bounced_email')
    op.drop_column('companies', 'reply_received')
    op.drop_column('companies', 'whatsapp_sent')
    op.drop_column('companies', 'email_sent')
    op.drop_column('companies', 'payment_status')
    op.drop_column('companies', 'billing_status')
    op.drop_column('companies', 'order_value')
    op.drop_column('companies', 'po_number')
    op.drop_column('companies', 'order_date')
    op.drop_column('companies', 'order_received')
    op.drop_column('companies', 'next_followup_date')
    op.drop_column('companies', 'last_contact_date')
    op.drop_column('companies', 'lead_status')
    op.drop_column('companies', 'remarks')
    op.drop_column('companies', 'division')
    op.drop_column('companies', 'contact_person')
    # ### end Alembic commands ###
