"""add_contact_intelligence_fields

Revision ID: 85a9a288beac
Revises: 001_initial
Create Date: 2026-05-26 07:13:31.752699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85a9a288beac'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_won_customers_id', table_name='won_customers')
    op.drop_table('won_customers')
    op.add_column('companies', sa.Column('linkedin', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('contact_page', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('address', sa.Text(), nullable=True))
    op.drop_index('idx_companies_buying_window', table_name='companies')
    op.drop_index('idx_companies_icp_score', table_name='companies')
    op.drop_index('idx_companies_tier', table_name='companies')
    op.drop_constraint('fk_companies_lookalike', 'companies', type_='foreignkey')
    op.drop_column('companies', 'name_embedding')
    op.drop_index('idx_signals_active', table_name='company_intent_signals')
    op.drop_index('ix_lead_ratings_company_id', table_name='lead_ratings')
    op.drop_index('ix_persons_company_id', table_name='persons')
    op.drop_index('idx_pipeline_next_action_date', table_name='pipeline_stages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_pipeline_next_action_date', 'pipeline_stages', ['next_action_date'], unique=False)
    op.create_index('ix_persons_company_id', 'persons', ['company_id'], unique=False)
    op.create_index('ix_lead_ratings_company_id', 'lead_ratings', ['company_id'], unique=False)
    op.create_index('idx_signals_active', 'company_intent_signals', ['is_active'], unique=False)
    op.add_column('companies', sa.Column('name_embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_companies_lookalike', 'companies', 'companies', ['lookalike_source_id'], ['id'])
    op.create_index('idx_companies_tier', 'companies', ['calculated_tier'], unique=False)
    op.create_index('idx_companies_icp_score', 'companies', [sa.text('icp_score DESC')], unique=False)
    op.create_index('idx_companies_buying_window', 'companies', ['buying_window'], unique=False)
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'contact_page')
    op.drop_column('companies', 'linkedin')
    op.create_table('won_customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feature_vector', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('won_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='won_customers_company_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='won_customers_pkey')
    )
    op.create_index('ix_won_customers_id', 'won_customers', ['id'], unique=False)
    # ### end Alembic commands ###
