"""create_crm_activity_table

Revision ID: ca8b0ac5604d
Revises: f83484ca2a07
Create Date: 2026-05-26 11:23:23.963048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8b0ac5604d'
down_revision: Union[str, None] = 'f83484ca2a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
