"""create_crm_activities_table

Revision ID: f8beb6c27ca5
Revises: ca8b0ac5604d
Create Date: 2026-05-27 04:43:03.994341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8beb6c27ca5'
down_revision: Union[str, None] = 'ca8b0ac5604d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_activities_company_id'), 'pipeline_activities', ['company_id'], unique=False)
    op.create_index(op.f('ix_pipeline_activities_id'), 'pipeline_activities', ['id'], unique=False)
    op.drop_index('ix_activities_company_id', table_name='activities')
    op.drop_index('ix_activities_id', table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pipeline_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='activities_company_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name='activities_person_id_fkey'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_stages.id'], name='activities_pipeline_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='activities_pkey')
    )
    op.create_index('ix_activities_id', 'activities', ['id'], unique=False)
    op.create_index('ix_activities_company_id', 'activities', ['company_id'], unique=False)
    op.drop_index(op.f('ix_pipeline_activities_id'), table_name='pipeline_activities')
    op.drop_index(op.f('ix_pipeline_activities_company_id'), table_name='pipeline_activities')
    op.drop_table('pipeline_activities')
    # ### end Alembic commands ###
